# Generated by Django 5.2.6 on 2025-09-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaAfgRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('up', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('down', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('updated_time', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Da Afghanistan Bank Rate',
                'verbose_name_plural': 'Da Afghanistan Bank Rates',
            },
        ),
        migrations.CreateModel(
            name='KhorasanRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('up', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('down', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('updated_time', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khorasan Market Rate',
                'verbose_name_plural': 'Khorasan Market Rates',
            },
        ),
        migrations.CreateModel(
            name='SaraiRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('up', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('down', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('updated_time', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sarai Shahzada Rate',
                'verbose_name_plural': 'Sarai Shahzada Rates',
            },
        ),
    ]
