# Generated by Django 5.2.6 on 2025-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_daafgrate_currency_alter_khorasanrate_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daafgrate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='khorasanrate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sarairate',
            options={},
        ),
        migrations.AlterField(
            model_name='daafgrate',
            name='down',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='daafgrate',
            name='up',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='daafgrate',
            name='updated_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='khorasanrate',
            name='down',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='khorasanrate',
            name='up',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='khorasanrate',
            name='updated_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sarairate',
            name='down',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sarairate',
            name='up',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sarairate',
            name='updated_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
